name: Build & publish Gentlebot image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Smoke test
        run: |
          pip install -r requirements.txt
          python -m gentlebot --help

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract debug info
        if: failure()   # only run on failure
        run: |
          # Copy the unhashed list and lockfile out of the builder image
          docker create --name dbg builder-image:latest >/dev/null
          docker cp dbg:/app/requirements.unhashed.txt .
          docker cp dbg:/app/requirements.lock .
          docker cp dbg:/wheels ./wheels
          docker rm dbg >/dev/null
      - name: Upload debug artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: debug-info
          path: |
            requirements.unhashed.txt
            requirements.lock
            wheels/

